### ISSUE TITLE
Under which license is this library provided?

### ISSUE THREAD

**Issue by r4fterman** [xmlark/msv#12]
Place a LICENSE.md in the project to indicate the license terms under which this library is released.

**Comment by svanteschubert** [comment]
Sun Microsoft created the project and when Oracle bought Sun the Copyright went over to Oracle.
After the merger/purchase, Oracle added to the MSV sources explicitly the BSD-3 clause:
https://opensource.org/license/bsd-3-clause

**Comment by r4fterman** [comment]
Thanks for quick fix 👍
