### ISSUE TITLE
WSDLGrammarReaderController needs to have ability to set Entity Resolver

### ISSUE THREAD

**Issue by Orbisman** [xmlark/msv#7]
Using the downstream project Woodstox, there is a need to be able to add a custom EntityResolver, covered in [Ticket #175](https://github.com/FasterXML/woodstox/issues/175).  In order to do so, the WSDLGrammarReaderController class needs enhanced to allow a custom EntityResolver to be set and resolveEntity method called.

**Comment by svanteschubert** [comment]
Closing this issue: Fixed by merging #8
